- src/main.py
This redirects the logs to std_out, with the hope to finally see something on kibana.
> redirect to std output

- .github/workflows/deploy.yaml
This PR changes the deployment GitHub action to trigger an auto-deploy only on new tags. The rationale for this change is that the `ebbo` deployment in our infrastructure is currently set to pull from the `latest` image, which only gets a new version every tag and not on every commit to the main branch.
The result of this change (hopefully - unless I got something wrong 🙈) is that every time a new GitHub release is made:
- A new image with tag `latest` is built
- The autodeploy hook will trigger a restart of the deployment such that the new image gets used
> Autodeploy On New Tags

- src/off_chain/cow_endpoint_surplus.py
Follow-up PR to #33, which escalates the main logs to an error level, for the purpose of testing the relevant slack channel.
> make every log an error for testing slack

- src/off_chain/cow_endpoint_surplus.py
With this PR, we ask that all alternative solutions considered must satisfy:
`collected_fees + 0.001 >= simulated_cost`.
Since simulated_cost is usually overestimating costs, should we instead require something like:
`collected_fees >= 0.9 * simulated_cost`?
**UPDATE:** Switched to the 2nd option, i.e., the relative check.
> Require economic viability for alternative solutions

- .github/workflows/pull_request.yaml
- src/daemon.py
This PR proposes to remove the `--strict` option from the mypy check.
At the current state of the repo, it slows things down significantly, and it is not clear if the benefits are that important for now. Of course, we want a stable monitoring tool, and eventually we should clean up the code and do proper type annotations, but now it seems it will take a very long time to have something working reasonably, partly because the --`strict` makes it much harder to merge PR #18, which adds fundamental functionality to the tool.
> remove strict option from mypy

- src/monitoring_tests/template_test.py
- tests/e2e/test.py
Quoting failed since the endpoint expects a "buyAmountAfterFee" field for buy orders. The correct field is now chosen for sell and buy orders.
> Fix error for partially-fillable buy orders

- src/monitoring_tests/fee_monitoring/fee_monitoring.py
- src/monitoring_tests/template_test.py
- tests/e2e/test.py
The hash 0xda857a0db563dae564b09febb683fff6150628c1706afc9ebd961c194ca29c5e
contains a partially-fillable order with an executed amount which is too small
to pay for fees. This resulted in the hash being rechecked over and over.
This error is now handled by logging an error and letting the test succeed.
This catches the errors `'NoLiquidity'` and `'SellAmountDoesNotCoverFees'`.
> Quote test ignores some errors now

- src/monitoring_tests/reference_solver_surplus_test.py
If quasimodo does not return a valid response, instead of emitting an error and retrying a hash, we now emit a warning and do not try the hash again.
This is just a hotfix. To solve the underlying issue, we should
- add error handling using custom exceptions
- let tests fail gracefully by removing hashes after some retries
- find the bug in how we call quasimodo
> Change handling of quasimodo error

- src/apis/solverapi.py
- src/monitoring_tests/reference_solver_surplus_test.py
This PR adds logging of the solution generated by the reference solver, whenever this (in isolation) gives more surplus to an order that is executed by some solver in the competition.
> Log reference solver (i.e., Quasimodo) solution when generating a ref_solver-surplus-ebbo error

- src/monitoring_tests/cost_coverage_per_solver_test.py
Fixes #71 by adding one more case to an `if ... else` block.
This was tested locally for specific hashes (e.g. `0x71cefc37510c2e00e4d345c0cf84afc7dfd0f397f39275211ea662e355a1fb6e`) where the test failed before.
> Add new score reporting to cost coverage test

- src/monitoring_tests/partially_fillable_fee_quote_test.py
- src/monitoring_tests/reference_solver_surplus_test.py
- src/monitoring_tests/solver_competition_surplus_test.py
This PR mutes most alerts currently raised in the repo:
- All alerts from the quote test are removed.
- All alerts form the reference solver test are removed.
- ~In the solver competition test, only those violations raise an alert where the reference solver is BaselineSolver.~ (edit: the solver competition test was not changed)
The test on cost coverage for partially fillable orders and the summary on cost coverage per solver (edit: and the solver competition test) are not changed. They will be relevant for the upcomming changes with regards to letting solvers choose fees.
This is another attempt at addressing #59.
> Mute most alerts

- README.md
- src/apis/web3api.py
This'll allow the user to specify any node provider instead of just using Infura
> Allow setting Node URL as HTTP Provider

- src/monitoring_tests/cost_coverage_per_solver_test.py
This PR removes the score discount code path as there is no such option for submitting a score anymore. This closes issue #73 .
> [EASY] Remove score discount code path

- src/apis/web3api.py
This PR adds a very simple function in the web3, where one can provide a tx hash and gets back the block number where the tx took place.
(Context: I would like to fetch the block number so that I can then search for MEV Blocker kickbacks within that block)
> [EASY] Web3 API update: Get block number from tx hash

- src/apis/web3api.py
This PR adjusts a bit some of the functionality of the web3 api and adds a function that computes the native eth transfers to a target address. This again is needed for the PR that tracks the MEV Blocker kickbacks (that will be a follow-up to this PR).
> Update web3 api to compute eth transfers to an address

- src/apis/web3api.py
This minor PR attempts to fix [this](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d%2Fd,to:now))&_a=(columns:!(log),filters:!(),index:ea511870-d9b3-11ed-a9d0-a17451f01cc1,interval:auto,query:(language:kuery,query:'%22invalid%20from%20and%20to%20block%20combination%22'),sort:!(!('@timestamp',desc)))) exception, that is happening from time to time.
> fix minor issue in get_filtered_receipts

- src/apis/tenderlyapi.py
Adds an API for calling tenderly to simulate solutions from the competition endpoint.
It requires to set the environment variables `TENDERLY_USER`, `TENDERLY_PROJECT`, and `TENDERLY_ACCESS_KEY`.
Example usage is
```python
from src.apis.orderbookapi import OrderbookAPI
from src.apis.tenderlyapi import TenderlyAPI
orderbook_api = OrderbookAPI()
tenderly_api = TenderlyAPI()
tx_hash = "0xfabafaf60c538d22956e5ffe67512ba9ea29f0843fa80e2a1e1a7bc2ec8a96e9"
competition_data = orderbook_api.get_solver_competition_data(tx_hash)
solution = competition_data["solutions"][-1]
block_number = competition_data["competitionSimulationBlock"]
internalize = False
simulation_result = tenderly_api.simulate_solution(solution, block_number, internalize)
```
> Add tenderly api to simulate solutions

- src/daemon.py
- src/monitoring_tests/combinatorial_auction_surplus_test.py
- tests/e2e/combinatorial_auction_surplus_test.py
We are thinking about implementing combinatorial auctions. This would include filtering out solutions which do not provide more surplus on individual sell token-buy token pairs compared to solutions only including that token pair.
The test in this PR checks if the winning solution would have been filtered out based on this criterion.
One difference to the competition surplus test is that the test in this PR checks token pairs and not orders.
Potentially we want to check more in this test. E.g.
- Who would have won the auction with the filtering rule?
- Who would have won the auction with the option to declare multiple winners?
- What would the benefit in surplus have been?
Todo
> Test comparable to combinatorial auction filtering

- src/monitoring_tests/combinatorial_auction_surplus_test.py
- tests/e2e/combinatorial_auction_surplus_test.py
Objective in competition data is in wei, the rest of the test works with
ETH. With this fix, the objective is now correctly scaled to ETH as well.
> Fix scaling of objective in combinatorial auction test

- src/apis/orderbookapi.py
- src/monitoring_tests/combinatorial_auction_surplus_test.py
- src/monitoring_tests/solver_competition_surplus_test.py
- tests/e2e/combinatorial_auction_surplus_test.py
- tests/e2e/surplus_test.py
This PR addresses #90 for the competition surplus test and combinatorial auction test.
The main changes are:
- Order information is fetched from the orderbook orders endpoint.
- Execution data is obtained via the new data in the solver competition endpoint.
- Fees and costs are not explicitly part of the test anymore.
Before, information on trades (order data and order execution) were read from calldata. For non-winning solutions this is not possible anymore. For the winning solution it is still possible. But due to changes to the ordering of orders in the competition data, it was not easy for me to reconstruct the link from uid to trade. Thus, all information is not obtained through the orderbook api.
In principle, information on fees for non-winning solutions could be computed from …
> Change surplus based tests to use new data from orderbook

- src/apis/auctioninstanceapi.py
Update urls for auction instances. The old url made all tests with the reference solver fail automatically.
This closes #100.
> Add new urls for auction instances

- src/monitoring_tests/combinatorial_auction_surplus_test.py
The combinatorial auction test did never create an alert because the name of the baseline solver was written incorrectly. The name is fixed now, from `BaselineSolver` to `baseline`. The latter is the name used in the solver competition endpoint since colocation.
> Fix name of baseline solver in combinatorial auction test

- src/daemon.py
This PR disables the cost coverage test. We can reactivate it later if we get access to protocol fee policies from the orderbook api, see https://github.com/cowprotocol/services/issues/2642.
This closes #104.
> Disable cost coverage test

- contracts/cowamm_constantproduct.py
- src/daemon.py
- src/monitoring_tests/cowamm_commitment_test.py
- tests/e2e/cowamm_commitment_test.py
With enabling phase 2 of CoW AMM, solvers can execute CoW AMM orders with custom amounts. This requires commiting and uncommiting the order in the CoW AMM smart contract. Not uncommiting the order is a violation of social consensus rules since it prevents the default order from getting executed.
This PR implements a test where after every settlement which contains a precommit interaction from the CoW AMM address the commited order for that address is checked.
Since there seem to be no commits so far, the code is a bit difficult to test. I added a test with tailored call data.
> Add test for CoW AMM commitment

- src/constants.py
This PR increases the threshold for alerts in the buffers value test. The test is meant mostly as a monitoring/logging test so having a relatively low value doesn't make much sense.
> Increase buffer value test threshold

- src/constants.py
- src/monitoring_tests/mev_blocker_kickbacks_test.py
Noticed that the threshold is relatively high for alerts, given the current value of ETH. Also noticed that we get a lot of meaningless logs so decided to reduce those as well.
> Reduce MEV Blocker refunds test logs

- src/daemon.py
This PR removes tests.
There have been problems with long delays in EBBO tests. This is probably due to the number of tests run and their efficiency. To see where the issues are coming from and for general clean up, some tests are removed from the daemon.
- Reference solver surplus test: does not work at the moment.
- Buffer monitoring test: not related to EBBO and seems to slow down the loop significantly
- CoW AMM commitment test: obsolete with the new version of CoW AMMs
For now the code for tests is not removed completely as they can still be run manually. Longterm, all of the code should be removed as well.
> Remove tests

- src/apis/web3api.py
This PR adds handling for general exceptions in some web3 functions.
There are crashes of the EBBO pod related to fetching data using web3py. The proposed change would handle those errors more gracefully and also show which errors are raised so they can be handled more explicitly.
> Handle more exceptions in web3

- src/daemon.py
It was observed that the daemon has become very slow and not working as expected. For that, this PR proposes to disable the CombinatorialAuctionSurplusTest and the UniformDirectedPricesTest, as both are non-actionable, and with the hope that the daemon will start working again as expected.
> Disable more tests

- src/constants.py
- src/monitoring_tests/solver_competition_surplus_test.py
This PR changes the threshold for generating alerts to 0.05ETH (up from 0.005 ETH).
Info logs are generated at 0.0005ETH as before.
The threshold is increased so that only cases which require attention create alerts. Other cases are still logged.
> Increase surplus theshold for alerts

- src/constants.py
- src/daemon.py
- src/monitoring_tests/high_score_test.py
- tests/e2e/high_score_test.py
This PR adds a very simple alerts that checks if the winning score for auctions that made it onchain is larger than some threshold. Very large scores might be an indication of bogus native prices so this is one way to detect those cases.
I realized that currently the tests, as they are set up, will pass if the wrapper function returns True. But this doesn't really check the logic the test implements, so in order to properly see logs and behavior, one needs to run the tests as follows. E.g:
`python -m pytest --log-cli-level=DEBUG  tests/e2e/high_score_test.py`
> Add high score alert

- src/monitoring_tests/combinatorial_auction_surplus_test.py
- src/monitoring_tests/high_score_test.py
- src/monitoring_tests/reference_solver_surplus_test.py
- src/monitoring_tests/solver_competition_surplus_test.py
- src/monitoring_tests/uniform_directed_prices_test.py
This PR changes how transaction hashes are fetched from competition data.
To support multiple winners, the competition data format was changed to allow for multiple transactions to be associated to an auction. This meant, that instead of a `"transactionHash"` field containing a string, a `"transactionHashes"` field containing a vector of strings is stored. This PR, changes the code to use the new convention.
> Fix getting transaction hash from competition data

- src/apis/web3api.py
- tests/e2e/mev_blocker_kickbacks_test.py
@fhenneke observed that high MEV Blocker refund alerts were missing. Had a look and it turns out that a topic check
```
txs["topics"][0].hex()  == "0x3d0ce9bfc3ed7d6862dbb28b2dea94561fe714a1b4d019aa8af39730d1ad7c3d"
```
started failing because the left-hand side didn't have the prefix "0x".
Not sure why this stopped working, but in any case, this PR proposes a slightly more robust way of doing the check.
Also added a test to demonstrate the fix works. Again, the only meaningful way of running the test is by having it print the logs as well
` python -m pytest --log-cli-level=DEBUG tests/e2e/mev_blocker_kickbacks_test.py`
> Fix MEV Blocker kickbacks test

- src/apis/orderbookapi.py
- src/apis/web3api.py
- src/constants.py
- src/daemon.py
- src/monitoring_tests/buffers_monitoring_test.py
- src/monitoring_tests/combinatorial_auction_surplus_test.py
- src/monitoring_tests/cost_coverage_zero_signed_fee.py
- src/monitoring_tests/high_score_test.py
- src/monitoring_tests/mev_blocker_kickbacks_test.py
- src/monitoring_tests/partially_fillable_cost_coverage_test.py
- src/monitoring_tests/reference_solver_surplus_test.py
- src/monitoring_tests/solver_competition_surplus_test.py
- src/monitoring_tests/uniform_directed_prices_test.py
This PR proposes some minimal changes so that the daemon can be deployed on all chains. Note that constants/thresholds have not been edited, so the current values only make sense for chains where the native token is ETH.
> Adapt code to run more easily on other chains
